version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://station_user:station_password@db:5432/station_ops
      - SECRET_KEY=station-ops-secret-key-change-in-production-2024
      - CORS_ORIGINS_STR=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    depends_on:
      db:
        condition: service_healthy
    networks:
      - station-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - station-network
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=station_ops
      - POSTGRES_USER=station_user
      - POSTGRES_PASSWORD=station_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - station-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U station_user -d station_ops"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  backend_data:

networks:
  station-network:
    driver: bridge